name: pysourceCI
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check python installation
        run: bash src.sh -v 3.12.0 -d /usr/src
